#include<iostream.h>
#include<conio.h>
 int marksheet(int a,float b)
 int marksheet(int a,int b)
 int marksheet(int a,float b,float c)
 int marksheet(int a,int b)
 int main()
{
   clrscr();
   cout <<"function1"<<marksheet (10,10)<<endl;
   cout <<"function2"<<marksheet (2,10)<<endl;
   cout <<"function3"<<marksheet (10,20,3)<<endl;
   cout <<"function4"<<marksheet (20,4)<<endl;
   int marksheet (int a, float b)
   {
     return a+b;
   }
   int marksheet (int a,int b)
   {
	return a-b;
   }
   int marksheet (int a, int b, float c)
   {
    return a*b*c;
   }
   int marksheet (int a,int b)
   {
	return a/b;
   }
   getch();
   return 0;
}